# Generated by Django 5.2.17 on 2026-09-04 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ValidationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rule_code", models.CharField(max_length=100)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("warn", "Warn"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=10,
                    ),
                ),
                ("detail", models.TextField(blank=True)),
                ("checked_at", models.DateTimeField(auto_now=True)),
                (
                    "extracted_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_results",
                        to="documents.extractedfield",
                    ),
                ),
            ],
            options={
                "ordering": ["extracted_field", "rule_code"],
                "indexes": [
                    models.Index(fields=["outcome"], name="validation__outcome_34e70f_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("extracted_field", "rule_code"),
                        name="validationresult_one_row_per_rule_per_field",
                    )
                ],
            },
        ),
    ]
