# Generated by Django 5.2.17 on 2026-09-04 08:43

import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LogicalDocument",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "page_indexes",
                    models.JSONField(
                        default=list,
                        help_text="Zero-based page indexes of the source file this document occupies, e.g. [0, 1].",
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("commercial_invoice", "Commercial invoice"),
                            ("house_bill_of_lading", "House bill of lading"),
                            ("master_bill_of_lading", "Master bill of lading"),
                            ("arrival_notice", "Arrival notice"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=30,
                    ),
                ),
                (
                    "doc_type_confidence",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("identified", "Identified"),
                            ("extracting", "Extracting"),
                            ("needs_review", "Needs review"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="identified",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["source_file", "id"],
            },
        ),
        migrations.CreateModel(
            name="ExtractionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("model_id", models.CharField(max_length=200)),
                ("prompt_version", models.CharField(max_length=50)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("input_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("output_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("error", models.TextField(blank=True)),
                (
                    "logical_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extraction_runs",
                        to="documents.logicaldocument",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SourceFile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "sha256",
                    models.CharField(
                        help_text="SHA-256 of the file's bytes. The idempotency key: the same file ingested twice resolves to this row and never produces a second billable extraction.",
                        max_length=64,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-f]{64}$",
                                "Must be a SHA-256 as 64 lowercase hexadecimal characters.",
                            )
                        ],
                    ),
                ),
                ("original_filename", models.CharField(max_length=500)),
                ("mime_type", models.CharField(default="application/pdf", max_length=100)),
                ("byte_size", models.PositiveBigIntegerField()),
                ("page_count", models.PositiveIntegerField()),
                ("received_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "received_via",
                    models.CharField(
                        choices=[("email", "Email"), ("sftp", "SFTP"), ("upload", "Upload")],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("processing", "Processing"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                        ],
                        default="received",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at"],
                "indexes": [
                    models.Index(fields=["status"], name="documents_s_status_eacd91_idx"),
                    models.Index(fields=["-received_at"], name="documents_s_receive_d4b0a9_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("index", models.PositiveIntegerField()),
                ("width", models.FloatField()),
                ("height", models.FloatField()),
                ("has_text_layer", models.BooleanField()),
                (
                    "source_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="documents.sourcefile",
                    ),
                ),
            ],
            options={
                "ordering": ["source_file", "index"],
            },
        ),
        migrations.AddField(
            model_name="logicaldocument",
            name="source_file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logical_documents",
                to="documents.sourcefile",
            ),
        ),
        migrations.CreateModel(
            name="ExtractedField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("field_key", models.CharField(max_length=100)),
                ("value_raw", models.TextField(blank=True)),
                ("value_normalised", models.TextField(blank=True)),
                (
                    "confidence",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ]
                    ),
                ),
                ("page_index", models.PositiveIntegerField(blank=True, null=True)),
                ("bbox", models.JSONField(blank=True, null=True)),
                (
                    "threshold_applied",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ]
                    ),
                ),
                (
                    "routing",
                    models.CharField(
                        choices=[("auto", "Automatic"), ("review", "Human review")], max_length=10
                    ),
                ),
                (
                    "extraction_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="documents.extractionrun",
                    ),
                ),
            ],
            options={
                "ordering": ["extraction_run", "field_key"],
                "indexes": [
                    models.Index(fields=["routing"], name="documents_e_routing_79d61b_idx"),
                    models.Index(fields=["field_key"], name="documents_e_field_k_9ea826_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("confidence__gte", 0.0), ("confidence__lte", 1.0)),
                        name="extractedfield_confidence_is_a_probability",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("threshold_applied__gte", 0.0), ("threshold_applied__lte", 1.0)
                        ),
                        name="extractedfield_threshold_is_a_probability",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("confidence__lt", models.F("threshold_applied")),
                                ("routing", "review"),
                            ),
                            models.Q(
                                ("confidence__gte", models.F("threshold_applied")),
                                ("routing", "auto"),
                            ),
                            _connector="OR",
                        ),
                        name="extractedfield_routing_follows_confidence_alone",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="extractionrun",
            index=models.Index(fields=["status"], name="documents_e_status_9581e3_idx"),
        ),
        migrations.AddConstraint(
            model_name="page",
            constraint=models.UniqueConstraint(
                fields=("source_file", "index"), name="page_unique_per_file"
            ),
        ),
        migrations.AddIndex(
            model_name="logicaldocument",
            index=models.Index(fields=["status"], name="documents_l_status_677202_idx"),
        ),
        migrations.AddIndex(
            model_name="logicaldocument",
            index=models.Index(fields=["doc_type"], name="documents_l_doc_typ_5a79e0_idx"),
        ),
        migrations.AddConstraint(
            model_name="logicaldocument",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("doc_type_confidence__gte", 0.0), ("doc_type_confidence__lte", 1.0)
                ),
                name="logicaldocument_confidence_is_a_probability",
            ),
        ),
    ]
